### ISSUE TITLE
[Feature Request] Change directory for search

### ISSUE THREAD

**Issue by ese-s** [AlUlkesh/sd_search_model#3]
This extension is great but I recently changed my model directory using the COMMANDLINE_ARG  and this extension only searches the models folder in the web_ui, is there a way i can change the search directory?

**Comment by AlUlkesh** [comment]
Which command line parameter is that exactly?

**Comment by ese-s** [comment]
In the webuser.bat on the webui I put COMMANDLINE_ARGS= --ckpt-dir "D:\Stable Diffusion\Models" to add a model directory but this extension doesn't find the models in that directory, it always defaults searching for models in "C:\Users\me\stable-diffusion-webui\models" for example so I was wondering if there was a way to change that. Sorry, I didn't make that clear enough.

**Comment by AlUlkesh** [comment]
Thanks for the clarification. Can you check if this commit works for you?

**Comment by ese-s** [comment]
when launching webui-bat i get

**stable-diffusion-webui\extensions\sd_search_model\scripts\sd_search_model.py", line 104, in ssm_generate
    return hashes
UnboundLocalError: local variable 'hashes' referenced before assignment**

**Comment by ese-s** [comment]
sorry the full error is: 
**Error executing callback ui_tabs_callback for C:\Users\me\stable-diffusion-webui\extensions\sd_search_model\scripts\sd_search_model.py
Traceback (most recent call last):
  File "C:\Users\me\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "C:\Users\me\stable-diffusion-webui\extensions\sd_search_model\scripts\sd_search_model.py", line 218, in on_ui_tabs
    ssm_generate()
  File "C:\Users\me\stable-diffusion-webui\extensions\sd_search_model\scripts\sd_search_model.py", line 104, in ssm_generate
    return hashes
UnboundLocalError: local variable 'hashes' referenced before assignment**

**Comment by AlUlkesh** [comment]
That suggests it doesn't find any model files.

When you said `D:\Stable Diffusion\Models` is your new model directory, I assumed it follows the same convention as when it is under webui. So sd models would be in a subdirectory `Stable-diffusion`. That however seems not to be the case.

Please try the new commit. I don't append a subdir anymore there.

**Comment by ese-s** [comment]
this works great now thank you very much!

**Comment by ese-s** [comment]
hmm actually this now has an error when the "switch to/from one-line display" is pressed:

  *File "C:\Users\me\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\me\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Users\me\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\me\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\me\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\me\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\me\stable-diffusion-webui\extensions\sd_search_model\scripts\sd_search_model.py", line 187, in ssm_radio_change
    choice_checkpoint_info = sd_models.CheckpointInfo(model_path)
  File "C:\Users\me\stable-diffusion-webui\modules\sd_models.py", line 48, in __init__
    self.sha256 = hashes.sha256_from_cache(self.filename, "checkpoint/" + name)
  File "C:\Users\me\stable-diffusion-webui\modules\hashes.py", line 51, in sha256_from_cache
    ondisk_mtime = os.path.getmtime(filename)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\me\\stable-diffusion-webui\\models\\Stable-diffusion\\comicBabes_v1.safetensors'**

**Comment by AlUlkesh** [comment]
Continued here: #4
